const assert=require('node:assert/strict');
const fs=require('node:fs');
const http=require('node:http');
const path=require('node:path');
const {chromium}=require('playwright');
const rules=require('./schedule-rules');
const meeting=require('./meeting-rules');

function domainTests(){
  const month={id:1,level:'month',title:'3#楼至5层',start:'2026-09-01',end:'2026-09-30',goal:{building:'3#楼',stage:'主体结构',mode:'milestone',baseline:1,target:5,unit:'层',node:'梁板浇筑完成'}};
  const week={...month,id:2,level:'week',title:'至2层',start:'2026-09-14',end:'2026-09-20',parentId:1,goal:{...month.goal,target:2}};
  const day={id:3,level:'day',parentId:2,title:'2层浇筑',start:'2026-09-18',end:'2026-09-18',dailyTarget:100,scheduleLink:{weekId:2,monthId:1,milestone:2,closesNode:true}};
  const plans=[month,week,day];
  rules.validatePlans([],plans,[]);
  assert.equal(rules.summary(month,plans,[]).actual,1,'planned week never advances actual month');
  const partial=meeting.confirm({taskId:30,date:day.start},day,80,'测试','now');
  assert.equal(rules.summary(month,plans,[partial]).actual,1);
  const completed=meeting.confirm({taskId:30,date:day.start},day,100,'测试','now');
  assert.equal(rules.summary(month,plans,[completed]).actual,2);
  assert.equal(rules.summary(month,plans,[completed]).rate,25);
  assert.equal(rules.summary(week,plans,[completed]).rate,100);
  assert.equal(rules.summary(month,plans,[{...completed,scheduleSnapshot:{...completed.scheduleSnapshot,milestone:3}}]).actual,1,'no jumping missing floor2');
  assert.equal(rules.summary(month,plans,[{...completed,scheduleSnapshot:{...completed.scheduleSnapshot,closesNode:false}}]).actual,1,'partial work never closes concrete node');
  assert.throws(()=>rules.validateDay({...day,dailyTarget:80},plans));
  assert.throws(()=>rules.validateGoal({...week,goal:{...week.goal,target:6}},plans));
  assert.throws(()=>rules.validateDay({...day,start:'2026-09-21',end:'2026-09-21'},plans));
  assert.throws(()=>rules.validatePlans(plans,plans.map(p=>p.id===2?{...p,parentId:99}:p),[completed]));
  rules.validatePlans(plans,plans.map(p=>p.id===1?{...p,title:'修改显示名称'}:p),[completed]);
  assert.equal(rules.weeks(2026,8).length,6);
  assert.deepEqual(rules.weeks(2026,9)[0],{start:'2026-08-31',end:'2026-09-06'});
  const october={...month,id:11,start:'2026-10-01',end:'2026-10-31'};
  const crossWeek={...week,id:12,parentId:11,start:'2026-09-28',end:'2026-10-04'};
  const crossDay={...day,id:13,parentId:12,start:'2026-10-01',end:'2026-10-01',scheduleLink:{...day.scheduleLink,weekId:12,monthId:11}};
  rules.validatePlans([],[october,crossWeek,crossDay],[]);
  assert.throws(()=>rules.validateDay({...crossDay,start:'2026-09-30',end:'2026-09-30'},[october,crossWeek]));
  const qm={...month,goal:{...month.goal,mode:'quantity',baseline:0,target:10,unit:'吨'}};
  const qw={...week,goal:{...qm.goal}};
  const qd={...day,scheduleLink:{weekId:2,monthId:1,amount:2,capacity:2,workKey:'rebar2t'}};
  const qplans=[qm,qw,qd];rules.validatePlans([],qplans,[]);
  const r=meeting.confirm({taskId:30,date:'2026-09-18'},qd,75,'测试','now');
  assert.equal(rules.summary(qw,qplans,[r]).rate,15,'1.5t out of weekly10t');
  const carry=rules.carry(qd,r);assert.equal(carry.amount,0.5);assert.equal(carry.workKey,'rebar2t');
  const next=meeting.confirm({taskId:31,date:'2026-09-19'},{...qd,id:4,scheduleLink:carry},100,'测试','now');
  assert.equal(rules.summary(qm,qplans,[r,next,next]).actual,2,'dedupe same execution');
  assert.equal(rules.summary(qm,qplans,[r,next,{...next,taskId:32}]).actual,2,'cap carried scope');
  assert.equal(rules.summary(qm,qplans,[r,next],'2026-09-18').actual,1.5);
  const wm={...qm,goal:{...qm.goal,mode:'weight',target:100,unit:'份额'}};
  const ww={...qw,goal:{...wm.goal,monthShare:40}};
  const wd={...qd,scheduleLink:{...qd.scheduleLink,amount:50,capacity:50}};
  rules.validatePlans([],[wm,ww,wd],[]);
  const wr=meeting.confirm({taskId:30,date:'2026-09-18'},wd,100,'测试','now');
  assert.equal(rules.summary(wm,[wm,ww,wd],[wr]).actual,20,'50% weekly of40 monthly points');
  console.log('PASS domains: stable IDs, milestone1→5, no planned advancement, no floor gaps, quantity75%→1.5t, carryover caps, explicit weights, natural weeks, date/range guards');
}

(async()=>{
  domainTests();
  const publicFiles=new Set(['index.html','styles.css','app.js','server-bridge.js','meeting-rules.js','schedule-rules.js','schedule-recognition.js','schedule-recognition-ui.js','schedule-ui.js','vendor/jszip.min.js']);
  const server=http.createServer((req,res)=>{
    const file=req.url==='/'?'index.html':req.url.slice(1);
    if(!publicFiles.has(file)){res.writeHead(404);res.end();return;}
    res.writeHead(200,{'Content-Type':file.endsWith('.js')?'text/javascript':file.endsWith('.css')?'text/css':'text/html; charset=utf-8'});
    res.end(fs.readFileSync(path.join(__dirname,file)));
  });
  await new Promise(r=>server.listen(0,'127.0.0.1',r));
  let browser;
  try{
    browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH||'C:/Program Files/Google/Chrome/Application/chrome.exe'});
    const page=await browser.newPage({viewport:{width:1440,height:1000}});page.setDefaultTimeout(10000);
    const errors=[];page.on('pageerror',e=>errors.push(e.message));
    await page.goto(`http://127.0.0.1:${server.address().port}/`);await page.waitForLoadState('networkidle');
    await page.locator('#loginForm [name="account"]').fill('chen.pm');await page.locator('#loginForm [name="password"]').fill('001001');
    await page.locator('#loginForm [name="remember"]').check();await page.locator('#loginForm [type="submit"]').click();await page.locator('body.authenticated').waitFor();
    const stored=key=>page.evaluate(k=>JSON.parse(localStorage.getItem(k)||'[]'),key);
    await page.locator('[data-view="schedule"]').click();await page.locator('[data-plan-level="month"]').click();
    // An isolated uploaded image verifies goal edits do not replace original files.
    const chooserPromise=page.waitForEvent('filechooser');await page.locator('[data-upload-period-plan]').click();
    await (await chooserPromise).setFiles({name:'月计划原文件.png',mimeType:'image/png',buffer:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAusB9Wl6ZbsAAAAASUVORK5CYII=','base64')});
    await page.waitForFunction(()=>JSON.parse(localStorage.getItem('zhuxu-plans')||'[]').some(p=>p.attachments?.some(a=>a.name==='月计划原文件.png')));
    const originalFile=(await stored('zhuxu-plans')).find(p=>p.attachments?.some(a=>a.name==='月计划原文件.png'));
    await page.locator('[data-add-goal="month"]').click();
    const form=page.locator('#scheduleGoalForm');
    await form.locator('[name="title"]').fill('测试3#楼至5层');await form.locator('[name="building"]').fill('3#楼');
    await form.locator('[name="baseline"]').fill('1');await form.locator('[name="target"]').fill('5');
    await form.locator('[type="submit"]').click();await page.locator('#scheduleGoalDialog').waitFor({state:'hidden'});
    const month=(await stored('zhuxu-plans')).find(p=>p.title==='测试3#楼至5层');assert(month?.goal);
    await page.locator(`[data-arrange-week="${month.id}"]`).click();
    const today=new Date().toISOString().slice(0,10),yesterday=new Date(Date.now()-86400000).toISOString().slice(0,10);
    const range=rules.weeks(Number(today.slice(0,4)),Number(today.slice(5,7))).find(w=>w.start<=today&&w.end>=today);
    await form.locator('[name="title"]').fill('测试本周至2层');await form.locator('[name="start"]').fill(range.start);await form.locator('[name="end"]').fill(range.end);await form.locator('[name="target"]').fill('2');
    await form.locator('[type="submit"]').click();await page.locator('#scheduleGoalDialog').waitFor({state:'hidden'});
    const week=(await stored('zhuxu-plans')).find(p=>p.title==='测试本周至2层');assert.equal(week.parentId,month.id);
    assert((await page.locator(`[data-goal-item="${month.id}"]`).innerText()).includes('实际完成至 1层'));
    await page.locator('[data-daily-meeting]').click();await page.locator('#dailyMeetingDateInput').fill(yesterday);await page.locator('#dailyMeetingDateInput').dispatchEvent('change');
    await page.locator('[data-add-meeting-plan]').click();
    let row=page.locator('[data-meeting-plan-row]').last();await row.locator('[data-meeting-plan-title]').fill('测试2层梁板浇筑完成');
    await row.locator('[data-meeting-week]').selectOption(String(week.id));
    row=page.locator('[data-meeting-plan-row]').last();await row.locator('[data-meeting-closes]').check();
    assert((await row.innerText()).includes('测试3#楼至5层'));
    await page.locator('#dailyMeetingForm [type="submit"]').click();await page.locator('#dailyMeetingDialog').waitFor({state:'hidden'});
    const day=(await stored('zhuxu-plans')).find(p=>p.title==='测试2层梁板浇筑完成');assert.equal(day.scheduleLink.weekId,week.id);assert.equal(day.scheduleLink.monthId,month.id);
    await page.locator('[data-daily-meeting]').click();await page.locator('#dailyMeetingDateInput').fill(today);await page.locator('#dailyMeetingDateInput').dispatchEvent('change');
    const confirmation=page.locator('[data-meeting-today-row]').filter({hasText:'测试2层梁板浇筑完成'});
    await confirmation.locator('[data-meeting-today-progress]').fill('100');await confirmation.locator('[data-confirm-meeting-today]').click();
    assert(await confirmation.locator('[data-meeting-today-progress]').isDisabled());
    await page.locator('#dailyMeetingDialog [data-close-dialog]').first().click();
    await page.locator('[data-view="schedule"]').click();await page.locator('[data-plan-level="month"]').click();
    assert((await page.locator(`[data-goal-item="${month.id}"]`).innerText()).includes('实际完成至 2层 · 完成率 25%'));
    await page.locator(`[data-edit-goal="${month.id}"]`).click();await form.locator('[name="target"]').fill('6');await form.locator('[type="submit"]').click();
    assert(await page.locator('#scheduleGoalDialog').isVisible());assert((await form.locator('.goal-form-error').innerText()).includes('不能改动'));
    await form.locator('[name="target"]').fill('5');await form.locator('[name="title"]').fill('测试月目标改名');await form.locator('[type="submit"]').click();await page.locator('#scheduleGoalDialog').waitFor({state:'hidden'});
    await page.reload();await page.locator('body.authenticated').waitFor();await page.locator('[data-view="schedule"]').click();await page.locator('[data-plan-level="month"]').click();
    assert((await page.locator(`[data-goal-item="${month.id}"]`).innerText()).includes('实际完成至 2层'));
    assert.deepEqual((await stored('zhuxu-plans')).find(p=>p.id===originalFile.id).attachments,originalFile.attachments,'original uploaded file retained across all goal edits');
    await page.setViewportSize({width:667,height:710});await page.waitForFunction(()=>document.querySelector('#sidebar').getBoundingClientRect().right<=0);await page.locator(`[data-goal-item="${month.id}"]`).scrollIntoViewIfNeeded();await page.screenshot({path:path.join(__dirname,'qa-schedule-links-mobile.png')});
    assert.deepEqual(errors,[]);
    console.log('PASS UI: month→week→meeting day, explicit linkage, confirmed node rollup, target freeze/title rename, reload persistence, mobile goal list');
  }finally{await browser?.close();await new Promise(r=>server.close(r));}
})().catch(e=>{console.error(e);process.exitCode=1;});
