const { chromium } = require('playwright');
const JSZip = require('jszip');
const path = require('path');
const { pathToFileURL } = require('url');

const sampleImageFile = {
  name: '现场测试照片.png',
  mimeType: 'image/png',
  buffer: Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAusB9Wl6ZbsAAAAASUVORK5CYII=', 'base64')
};

async function login(page, account = 'chen.pm', password = '001001', remember = true) {
  await page.locator('#loginForm input[name="account"]').fill(account);
  await page.locator('#loginForm input[name="password"]').fill(password);
  if (remember) await page.locator('#loginForm input[name="remember"]').check();
  await page.locator('#loginForm').getByRole('button', { name: '登录平台' }).click();
  await page.locator('body.authenticated').waitFor();
}

(async () => {
  const root = __dirname;
  const url = pathToFileURL(path.join(root, 'index.html')).href;
  const browser = await chromium.launch({
    headless: true,
    executablePath: 'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe'
  });
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
  const consoleErrors = [];
  page.on('console', msg => { if (msg.type() === 'error') consoleErrors.push(msg.text()); });
  await page.goto(url);
  await page.evaluate(() => { localStorage.clear(); sessionStorage.clear(); });
  await page.reload();
  await page.waitForLoadState('networkidle');

  if (!(await page.locator('#loginScreen').isVisible())) throw new Error('Formal login page missing');
  await page.screenshot({ path: path.join(root, 'qa-login.png'), fullPage: true });
  await page.locator('#loginForm input[name="account"]').fill('chen.pm');
  await page.locator('#loginForm input[name="password"]').fill('wrong');
  await page.locator('#loginForm').getByRole('button', { name: '登录平台' }).click();
  if (!(await page.locator('#loginError').textContent()).includes('不正确')) throw new Error('Invalid password was not rejected');
  await login(page);
  if (!(await page.locator('#currentUserCard').getByText('陈海峰').isVisible())) throw new Error('Logged-in user was not bound to organization');

  if (await page.title() !== '筑序 · 施工效率驾驶舱') throw new Error('Unexpected title');
  if (await page.locator('#processRail .stage-button').count() !== 7) throw new Error('Stages not rendered');
  if (await page.locator('#taskList .task-item').count() < 6) throw new Error('Tasks not rendered');
  if (await page.locator('#organizationRoles .role-chip').count() < 5) throw new Error('Organization roles not rendered');
  await page.locator('#organizationButton').click();
  if (await page.locator('#organizationEditor .organization-person').count() < 8) throw new Error('Organization editor incomplete');
  await page.locator('#organizationForm').getByRole('button', { name: '保存组织架构' }).click();
  if (await page.locator('#organizationDialog').evaluate(dialog => dialog.open)) throw new Error('Organization dialog did not close');

  await page.locator('[data-stage="3"]').click();
  if (!(await page.locator('#stageDetail').innerText()).includes('砌体材料到货晚')) throw new Error('Stage interaction failed');

  await page.getByRole('button', { name: '有风险' }).click();
  if (await page.locator('#taskList .task-item').count() !== 2) throw new Error('Task filter failed');
  await page.getByRole('button', { name: '全部', exact: true }).click();

  await page.locator('#addTaskButton').click();
  await page.locator('#taskDialog input[name="title"]').fill('样板层机电综合验收');
  await page.locator('#taskDialog input[name="owner"]').fill('李工');
  await page.locator('#taskDialog input[name="creator"]').fill('赵工 · 安全员');
  await page.getByRole('button', { name: '创建任务' }).click();
  if (await page.locator('#taskDialog').evaluate(dialog => dialog.open)) throw new Error('Task dialog did not close');
  if (await page.locator('#taskList').getByText('样板层机电综合验收').count() !== 1) throw new Error('Task creation failed');
  if (!(await page.locator('#taskList').getByText('发起：赵工 · 安全员').isVisible())) throw new Error('Task creator was not saved');

  await page.locator('[data-view="schedule"]').click();
  if (await page.locator('#schedule [data-plan-level]').count() !== 4) throw new Error('Four plan levels were not rendered');
  await page.locator('#schedule .subview-action').click();
  await page.locator('#planForm input[name="title"]').fill('测试新增周计划');
  await page.locator('#planForm input[name="start"]').fill('2026-08-10');
  await page.locator('#planForm input[name="end"]').fill('2026-08-15');
  await page.locator('#planForm').getByRole('button', { name: '更新计划' }).click();
  if (!(await page.locator('#schedule').getByText('测试新增周计划').isVisible())) throw new Error('Manual plan was not added');
  await page.locator('#schedule .subview-action').click();
  await page.locator('[data-plan-mode="import"]').click();
  const xlsx = new JSZip();
  xlsx.file('xl/sharedStrings.xml', '<?xml version="1.0"?><sst><si><t>工作名称</t></si><si><t>3#楼9F墙柱钢筋绑扎</t></si><si><t>地下室消防管安装</t></si></sst>');
  xlsx.file('xl/worksheets/sheet1.xml', '<?xml version="1.0"?><worksheet><sheetData><row><c t="s"><v>0</v></c></row><row><c t="s"><v>1</v></c></row><row><c t="s"><v>2</v></c></row></sheetData></worksheet>');
  const xlsxBuffer = await xlsx.generateAsync({ type: 'nodebuffer' });
  await page.locator('#planImportInput').setInputFiles({ name: '周计划.xlsx', mimeType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', buffer: xlsxBuffer });
  await page.locator('#planRecognitionCandidates .candidate-row').first().waitFor();
  if (await page.locator('#planRecognitionCandidates .candidate-row').count() < 2) throw new Error('Plan file recognition failed');
  await page.locator('#planForm').getByRole('button', { name: '更新计划' }).click();
  if (!(await page.locator('#schedule').getByText('3#楼9F墙柱钢筋绑扎').isVisible())) throw new Error('Recognized plan was not written');
  await page.waitForTimeout(350);
  await page.screenshot({ path: path.join(root, 'qa-schedule.png'), fullPage: true });

  await page.locator('[data-view="tasks"]').click();
  if (await page.locator('#addTaskButton').isVisible()) throw new Error('Global new-task button should only appear on dashboard');
  await page.locator('[data-edit-task-row="1"]').click();
  await page.locator('#taskForm input[name="time"]').fill('12:10');
  await page.locator('#taskForm').getByRole('button', { name: '保存修改' }).click();
  if (!(await page.locator('#tasks').getByText('12:10').isVisible())) throw new Error('Task editing failed');
  await page.locator('#tasks .subview-action').click();
  await page.locator('[data-task-intake="file"]').click();
  const docx = new JSZip();
  docx.file('word/document.xml', '<?xml version="1.0"?><w:document xmlns:w="w"><w:body><w:p><w:r><w:t>地下室桥架安装复核</w:t></w:r></w:p><w:p><w:r><w:t>东侧临边防护整改</w:t></w:r></w:p></w:body></w:document>');
  const docxBuffer = await docx.generateAsync({ type: 'nodebuffer' });
  await page.locator('#taskImportInput').setInputFiles({ name: '生产经理日任务.docx', mimeType: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document', buffer: docxBuffer });
  await page.locator('#taskRecognitionCandidates .candidate-row').first().waitFor();
  if (await page.locator('#taskRecognitionCandidates .candidate-row').count() !== 2) throw new Error('Task file recognition failed');
  if (!(await page.locator('#taskRecognitionCandidates').getByText('机电工程师').first().isVisible())) throw new Error('Role matching failed');
  await page.screenshot({ path: path.join(root, 'qa-task-recognition.png') });
  await page.locator('#taskForm').getByRole('button', { name: '创建任务' }).click();
  if (!(await page.locator('#tasks').getByText('地下室桥架安装复核').isVisible())) throw new Error('Recognized tasks were not dispatched');
  await page.locator('#tasks .subview-action').click();
  await page.locator('[data-task-intake="voice"]').click();
  await page.locator('#voiceTranscript').fill('明天上午完成3号楼模板加固并通知质量员验收');
  await page.locator('#parseVoiceButton').click();
  if (await page.locator('#taskRecognitionCandidates .candidate-row').count() !== 1) throw new Error('Voice transcript was not parsed');
  await page.locator('#taskDialog').getByRole('button', { name: '关闭' }).click();

  await page.locator('[data-view="materials"]').click();
  if (await page.locator('#materials').getByRole('heading', { name: '材料与设备' }).count() !== 1) throw new Error('Resource navigation failed');
  if (!(await page.locator('#globalBackButton').isVisible())) throw new Error('Back button not visible in subview');
  if (await page.locator('#materials [data-resource-tab]').count() !== 4) throw new Error('Material, equipment, resource plan or procurement tabs missing');
  await page.locator('#materials [data-register-resource="material"]').click();
  await page.locator('#resourceEntryForm input[name="name"]').fill('测试钢筋原材');
  await page.locator('#resourceEntryForm input[name="brand"]').fill('测试钢厂');
  await page.locator('#resourceEntryForm input[name="spec"]').fill('HRB400E Φ20');
  await page.locator('#resourceEntryForm input[name="quantity"]').fill('18 t');
  await page.locator('#resourceEntryForm input[name="location"]').fill('3#楼 9F 墙柱');
  await page.locator('#resourceEntryForm input[name="certificates"]').setInputFiles({ name: '合格证.pdf', mimeType: 'application/pdf', buffer: Buffer.from('%PDF-1.4 test certificate') });
  await page.locator('#resourceEntryForm input[name="photos"]').setInputFiles(sampleImageFile);
  await page.locator('#resourceEntryForm').getByRole('button', { name: '保存登记' }).click();
  await page.locator('#resourceEntryDialog').waitFor({ state: 'hidden' });
  if (!(await page.locator('#materials').getByText('测试钢筋原材').isVisible())) throw new Error('Material entry was not saved');
  await page.screenshot({ path: path.join(root, 'qa-resource-ledger.png'), fullPage: true });
  await page.locator('#materials [data-resource-entry-detail]').filter({ hasText: '测试钢筋原材' }).click();
  await page.locator('#resourceDetailDialog [data-attachment-entry]').filter({ hasText: '合格证.pdf' }).click();
  await page.locator('#attachmentPreviewDialog').waitFor({ state: 'visible' });
  const attachmentSrc = await page.locator('#attachmentPreviewBody iframe').getAttribute('src');
  if (!attachmentSrc || !attachmentSrc.startsWith('blob:')) throw new Error('Uploaded PDF was not loaded from attachment storage');
  await page.locator('#attachmentPreviewDialog').getByRole('button', { name: '关闭' }).click();
  await page.locator('#resourceDetailDialog [data-attachment-entry]').filter({ hasText: sampleImageFile.name }).click();
  await page.locator('#attachmentPreviewDialog').waitFor({ state: 'visible' });
  const imageAttachmentSrc = await page.locator('#attachmentPreviewBody img').getAttribute('src');
  if (!imageAttachmentSrc || !imageAttachmentSrc.startsWith('blob:')) throw new Error('Uploaded image was not loaded from attachment storage');
  await page.screenshot({ path: path.join(root, 'qa-attachment-preview.png'), fullPage: true });
  await page.locator('#attachmentPreviewDialog').getByRole('button', { name: '关闭' }).click();
  await page.locator('#resourceDetailDialog').getByRole('button', { name: '关闭' }).last().click();
  await page.locator('#materials [data-resource-tab="equipment"]').click();
  await page.locator('#materials [data-register-resource="equipment"]').click();
  await page.locator('#resourceEntryForm input[name="name"]').fill('测试汽车吊');
  await page.locator('#resourceEntryForm input[name="brand"]').fill('徐工');
  await page.locator('#resourceEntryForm input[name="spec"]').fill('QY25K5');
  await page.locator('#resourceEntryForm input[name="quantity"]').fill('1 台');
  await page.locator('#resourceEntryForm input[name="location"]').fill('项目东门');
  await page.locator('#resourceEntryForm').getByRole('button', { name: '保存登记' }).click();
  if (!(await page.locator('#materials').getByText('测试汽车吊').isVisible())) throw new Error('Equipment entry was not saved');
  await page.locator('#materials [data-new-resource-plan]').click();
  if (await page.locator('#resourcePlanOwnerRole option').count() < 10) throw new Error('Resource plan roles are still limited');
  if (!(await page.locator('#resourcePlanOwnerRole option', { hasText: '施工员' }).count()) || !(await page.locator('#resourcePlanOwnerRole option', { hasText: '质量员' }).count())) throw new Error('Construction or quality role missing');
  await page.locator('#resourcePlanForm select[name="type"]').selectOption('equipment');
  await page.locator('#resourcePlanForm input[name="name"]').fill('测试塔吊使用计划');
  await page.locator('#resourcePlanForm input[name="quantity"]').fill('1 台');
  await page.locator('#resourcePlanForm input[name="due"]').fill('2026-08-18');
  await page.locator('#resourcePlanForm input[name="location"]').fill('3#楼北侧');
  await page.locator('#resourcePlanForm').getByRole('button', { name: '保存资源计划' }).click();
  if (!(await page.locator('#materials').getByText('测试塔吊使用计划').isVisible())) throw new Error('Resource plan was not saved');
  if (!(await page.locator('#materials').getByText('未来 7 天到场预报').isVisible())) throw new Error('Seven-day arrival forecast missing');
  await page.locator('#materials [data-resource-plan-detail]').filter({ hasText: '测试塔吊使用计划' }).click();
  if (!(await page.locator('#resourceDetailDialog').getByText('计划数量').isVisible())) throw new Error('Resource plan detail did not open');
  await page.locator('#resourceDetailDialog').getByRole('button', { name: '关闭' }).last().click();
  await page.locator('#materials [data-resource-tab="equipment"]').click();
  await page.locator('#materials [data-register-resource="equipment"]').click();
  await page.locator('#resourceEntryForm input[name="name"]').fill('测试塔吊使用计划');
  await page.locator('#resourceEntryForm input[name="brand"]').fill('中联重科');
  await page.locator('#resourceEntryForm input[name="spec"]').fill('TC6515');
  await page.locator('#resourceEntryForm input[name="quantity"]').fill('0.5 台');
  await page.locator('#resourceEntryForm input[name="location"]').fill('3#楼北侧');
  if (!(await page.locator('#resourcePlanMatch').inputValue())) throw new Error('Arrival was not automatically matched to a plan');
  await page.locator('#resourceEntryForm').getByRole('button', { name: '保存登记' }).click();
  await page.locator('#materials [data-resource-entry-detail]').filter({ hasText: '测试塔吊使用计划' }).click();
  if (!(await page.locator('#resourceDetailDialog').getByText('关联计划').isVisible())) throw new Error('Resource ledger detail did not open');
  await page.locator('#resourceDetailDialog').getByRole('button', { name: '关闭' }).last().click();
  await page.locator('#materials [data-resource-tab="plans"]').click();
  const partialPlanRow = page.locator('#materials [data-resource-plan-detail]').filter({ hasText: '测试塔吊使用计划' });
  if (!(await partialPlanRow.getByText('部分到场').isVisible()) || !(await partialPlanRow.getByText('余 0.5 台').isVisible())) throw new Error('Partial arrival progress was not calculated');
  await partialPlanRow.click();
  await page.screenshot({ path: path.join(root, 'qa-resource-detail.png'), fullPage: true });
  await page.locator('#resourceDetailDialog').getByRole('button', { name: '关闭' }).last().click();
  await page.waitForTimeout(350);
  await page.screenshot({ path: path.join(root, 'qa-resource-plans.png'), fullPage: true });

  await page.locator('[data-view="documents"]').click();
  if (await page.locator('#documents').getByRole('heading', { name: '资料完成情况' }).count() !== 1) throw new Error('Material arrival did not open document chain');
  if (!(await page.locator('#documents').getByText('见证取样').first().isVisible())) throw new Error('Steel sampling document was not generated');
  if (!(await page.locator('#documents [data-chain-tab]').filter({ hasText: '测试钢筋原材' }).isVisible())) throw new Error('Material arrival was not converted into a document chain');
  await page.locator('#documents .subview-action').click();
  await page.locator('#gateChainSelect').selectOption({ label: '测试钢筋原材' });
  if (!(await page.locator('#gateMaterialSummary').getByText('测试钢厂').isVisible())) throw new Error('Material brand/spec was not linked into document gate');
  await page.locator('#documentGateForm input[name="commissionFiles"]').setInputFiles({ name: '送检委托.pdf', mimeType: 'application/pdf', buffer: Buffer.from('%PDF-1.4 commission') });
  await page.locator('#documentGateForm input[name="reportFiles"]').setInputFiles({ name: '检测合格报告.pdf', mimeType: 'application/pdf', buffer: Buffer.from('%PDF-1.4 report') });
  await page.locator('#documentGateForm .gate-options label').first().click();
  await page.locator('#gateSubmitButton').click();
  await page.locator('#documentGateDialog').waitFor({ state: 'hidden' });
  if (!(await page.locator('#documents').getByText('资料门禁已放行').isVisible())) throw new Error('Generic material report did not release document gate');
  if (await page.locator('#documents .material-acceptance-row:not(.header)').count() < 5) throw new Error('Material documents were not consolidated by arrival batch');
  const testMaterialBatch = page.locator('#documents .material-acceptance-row').filter({ hasText: '测试钢筋原材进场验收' });
  await testMaterialBatch.getByRole('button', { name: '查看 / 编辑' }).click();
  if (!(await page.locator('#acceptanceExistingFiles').getByText('送检委托 · 1').isVisible()) || !(await page.locator('#acceptanceExistingFiles').getByText('检测报告 · 1').isVisible())) throw new Error('Commission/report uploads are not visible in consolidated acceptance details');
  const automaticOwner = await page.locator('#acceptanceDocumentEditor .acceptance-owner').first().inputValue();
  if (!automaticOwner.includes(' · ')) throw new Error('Document owner was not resolved to a person in the organization');
  await page.locator('#acceptanceDocumentEditor .acceptance-owner').first().fill('周海 · 技术负责人');
  await page.locator('#materialAcceptanceForm').getByRole('button', { name: '保存进场验收资料' }).click();
  await page.locator('#materialAcceptanceDialog').waitFor({ state: 'hidden' });
  await testMaterialBatch.getByRole('button', { name: '查看 / 编辑' }).click();
  if ((await page.locator('#acceptanceDocumentEditor .acceptance-owner').first().inputValue()) !== '周海 · 技术负责人') throw new Error('Manual document owner change did not persist');
  await page.screenshot({ path: path.join(root, 'qa-document-material-detail.png'), fullPage: true });
  await page.locator('#materialAcceptanceDialog').getByRole('button', { name: '关闭' }).first().click();
  await page.locator('#globalBackButton').click();
  if (!(await page.locator('#dashboard').isVisible())) throw new Error('Back to dashboard failed');

  await page.locator('[data-id="1"] .task-status').click();
  if (!(await page.locator('#documentGateDialog').isVisible())) throw new Error('Steel binding document gate did not open');
  await page.screenshot({ path: path.join(root, 'qa-document-gate.png') });
  await page.locator('#gateSubmitButton').click();
  await page.locator('#documentGateDialog').waitFor({ state: 'hidden' });
  if (!((await page.locator('[data-id="1"]').getAttribute('class')) || '').includes('todo')) throw new Error('Testing report should keep steel binding task pending');
  await page.locator('[data-id="1"] .task-status').click();
  await page.locator('#documentGateForm .gate-options label').first().click();
  if (!(await page.locator('#documentGateForm input[value="qualified"]').isChecked())) throw new Error('Qualified status could not be selected');
  await page.locator('#gateSubmitButton').click();
  await page.locator('#documentGateDialog').waitFor({ state: 'hidden' });
  if (!((await page.locator('[data-id="1"]').getAttribute('class')) || '').includes('doing')) throw new Error('Qualified report did not release steel binding task');
  if ((await page.evaluate(() => JSON.parse(localStorage.getItem('zhuxu-document-state')).steel.sampleStatus)) !== 'qualified') throw new Error('Document summary was not updated');
  await page.locator('#documentStrip').click();
  if (!(await page.locator('#documents').getByText('资料门禁已放行').isVisible())) throw new Error('Released document gate not shown');
  await page.locator('[data-chain-tab="concrete"]').click();
  if (!(await page.locator('#documents').getByText('试块留置').first().isVisible())) throw new Error('Concrete document chain missing');
  await page.locator('[data-chain-tab="waterproof"]').click();
  if (!(await page.locator('#documents').getByText('防水工程', { exact: true }).first().isVisible())) throw new Error('Waterproof document chain missing');
  await page.locator('[data-chain-tab="concrete"]').click();
  const concreteBatch = page.locator('#documents .material-acceptance-row').filter({ hasText: '混凝土进场验收' });
  await concreteBatch.getByRole('button', { name: '查看 / 编辑' }).click();
  await page.locator('#acceptanceDocumentEditor .acceptance-document-item').filter({ hasText: '混凝土强度报告' }).getByRole('button', { name: '催办' }).click();
  if (!(await page.locator('#followupDialog').isVisible())) throw new Error('Document follow-up dialog did not open');
  await page.locator('#followupForm .urgency-options label').first().click();
  if (!(await page.locator('#followupForm input[value="urgent"]').isChecked())) throw new Error('Urgency selection failed');
  const followupTitle = await page.locator('#followupForm input[name="title"]').inputValue();
  await page.locator('#followupForm').getByRole('button', { name: '发起催办' }).click();
  await page.locator('#followupDialog').waitFor({ state: 'hidden' });
  await page.locator('#materialAcceptanceDialog').getByRole('button', { name: '关闭' }).first().click();
  await page.locator('[data-view="followups"]').click();
  if (!(await page.locator('#followups').getByText(followupTitle).first().isVisible())) throw new Error('Follow-up was not saved');
  await page.waitForTimeout(350);
  await page.screenshot({ path: path.join(root, 'qa-followups.png'), fullPage: true });
  await page.reload();
  await page.waitForLoadState('networkidle');
  await page.locator('[data-view="followups"]').click();
  if (!(await page.locator('#followups').getByText(followupTitle).first().isVisible())) throw new Error('Follow-up did not persist after reload');
  await page.locator('#globalBackButton').click();
  await page.locator('[data-id="1"] [data-urge-task]').click();
  if ((await page.locator('#followupForm select[name="category"]').inputValue()) !== '工序催办') throw new Error('Task follow-up was not prefilled');
  await page.locator('#followupDialog').getByRole('button', { name: '关闭' }).click();
  await page.locator('#documentStrip').click();
  await page.waitForTimeout(350);
  await page.screenshot({ path: path.join(root, 'qa-documents.png'), fullPage: true });
  await page.locator('#globalBackButton').click();

  await page.locator('[data-view="quality"]').click();
  if (!(await page.locator('#quality').getByRole('heading', { name: '质量安全' }).isVisible())) throw new Error('Quality/safety page missing');
  await page.locator('#quality [data-quality-filter="pending"]').click();
  if (await page.locator('#quality [data-edit-quality]').count() !== 7) throw new Error('Rectification items are not listed');
  const firstQualityTitle = await page.locator('#quality [data-edit-quality]').first().locator('strong').innerText();
  await page.locator('#quality [data-edit-quality]').first().click();
  await page.locator('#qualityCheckForm input[name="beforePhotos"]').setInputFiles(sampleImageFile);
  await page.locator('#qualityCheckForm input[name="afterPhotos"]').setInputFiles(sampleImageFile);
  await page.locator('#qualityCheckForm select[name="status"]').selectOption('closed');
  await page.locator('#qualityCheckForm').getByRole('button', { name: '保存检查记录' }).click();
  await page.locator('#qualityCheckDialog').waitFor({ state: 'hidden' });
  await page.locator('#quality [data-quality-filter="all"]').click();
  if (!(await page.locator('#quality [data-edit-quality]').filter({ hasText: firstQualityTitle }).getByText('已闭环').isVisible())) throw new Error('Before/after rectification was not closed');
  await page.locator('#quality [data-quality-filter="safety"]').click();
  if (await page.locator('#quality [data-edit-inspection]').count() !== 12) throw new Error('Safety inspection batches are not listed');
  await page.locator('#quality [data-edit-inspection]').first().click();
  if (await page.locator('#inspectionIssueEditor .inspection-issue-editor-row').count() !== 3) throw new Error('Inspection does not contain multiple issue children');
  await page.locator('#addInspectionIssueButton').click();
  const newIssue = page.locator('#inspectionIssueEditor .inspection-issue-editor-row').last();
  await newIssue.locator('.inspection-issue-title').fill('临边防护栏杆缺失');
  if (!(await newIssue.locator('.inspection-issue-owner').inputValue()).includes('周强 · 安全员')) throw new Error('Inspection owner was not matched from organization');
  await newIssue.locator('.inspection-issue-owner').fill('吴晨 · 施工员');
  await newIssue.locator('.inspection-issue-title').fill('临边防护栏杆缺失并补设警示牌');
  if ((await newIssue.locator('.inspection-issue-owner').inputValue()) !== '吴晨 · 施工员') throw new Error('Manual inspection owner was overwritten');
  await newIssue.locator('.inspection-issue-location').fill('3#楼 8F 北侧');
  await page.locator('#inspectionBatchForm input[name="noticeFiles"]').setInputFiles({ name: '整改通知单.pdf', mimeType: 'application/pdf', buffer: Buffer.from('%PDF-1.4 notice') });
  await page.locator('#inspectionBatchForm input[name="replyFiles"]').setInputFiles({ name: '统一整改回复.pdf', mimeType: 'application/pdf', buffer: Buffer.from('%PDF-1.4 reply') });
  await page.locator('#inspectionBatchForm textarea[name="unifiedReply"]').fill('本次巡检提出的四项问题均已整改完成，现统一回复并申请复验。');
  const issueRows = page.locator('#inspectionIssueEditor .inspection-issue-editor-row');
  for (let index = 0; index < await issueRows.count(); index++) {
    const row = issueRows.nth(index);
    await row.locator('.inspection-issue-status').selectOption('closed');
    await row.locator('.inspection-issue-reply').fill(`第 ${index + 1} 项已完成整改并复验通过`);
    await row.locator('.inspection-issue-after').setInputFiles(sampleImageFile);
  }
  await page.screenshot({ path: path.join(root, 'qa-inspection-batch-dialog.png'), fullPage: true });
  await page.locator('#inspectionBatchForm').getByRole('button', { name: '保存巡检及整改' }).click();
  await page.locator('#inspectionBatchDialog').waitFor({ state: 'hidden' });
  const closedInspection = page.locator('#quality [data-edit-inspection]').filter({ hasText: '临边防护专项巡检' }).first();
  if (!(await closedInspection.getByText('4 项问题').isVisible()) || !(await closedInspection.getByText('统一回复已闭环').isVisible())) throw new Error('Inspection batch did not close with child issues');
  await closedInspection.click();
  await page.locator('[data-inspection-main-files="2"] [data-stored-file-index]').first().click();
  await page.locator('#attachmentPreviewDialog').waitFor({ state: 'visible' });
  await page.locator('#attachmentPreviewDialog').getByRole('button', { name: '关闭' }).first().click();
  await page.locator('#inspectionBatchDialog').getByRole('button', { name: '关闭' }).first().click();
  await page.screenshot({ path: path.join(root, 'qa-quality-closure.png'), fullPage: true });

  await page.locator('[data-view="team"]').click();
  if (!(await page.locator('#team').getByRole('heading', { name: '组织架构' }).isVisible())) throw new Error('Team page was not renamed to organization');
  if (await page.locator('#team .management-roster article').count() < 10) throw new Error('Project management roster incomplete');
  if (!(await page.locator('#team').getByText('138 0000 1001').isVisible())) throw new Error('Management phone is missing');
  await page.locator('#team [data-attendance]').click();
  await page.locator('#attendanceForm input[name="actual"]').fill('192');
  await page.locator('#attendanceForm input[name="planned"]').fill('190');
  await page.locator('#attendanceForm input[name="attendanceFile"]').setInputFiles({ name: '今日实名制打卡表.xlsx', mimeType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', buffer: xlsxBuffer });
  await page.locator('#attendanceForm').getByRole('button', { name: '保存考勤' }).click();
  await page.locator('#attendanceDialog').waitFor({ state: 'hidden' });
  if (!(await page.locator('#team').getByText('192 人').isVisible())) throw new Error('Attendance upload did not update site headcount');
  await page.locator('#team [data-attendance-history]').first().click();
  if (await page.locator('#attendanceHistoryBody [data-attendance-history-select]').count() < 6) throw new Error('Historical daily attendance is incomplete');
  if (!(await page.locator('#attendanceHistoryBody').getByText('今日实名制打卡表.xlsx').first().isVisible())) throw new Error('Attendance attachment is not visible in history');
  await page.locator('#attendanceHistoryBody [data-attendance-file]').click();
  await page.locator('#attachmentPreviewDialog').waitFor({ state: 'visible' });
  await page.locator('#attachmentPreviewDialog').getByRole('button', { name: '关闭' }).first().click();
  await page.locator('#attendanceHistoryBody [data-attendance-history-select]').filter({ hasText: '2026-08-09' }).click();
  const expiredSupplement = page.locator('#attendanceHistoryBody [data-supplement-attendance]');
  if (!(await expiredSupplement.isDisabled()) || !(await expiredSupplement.innerText()).includes('补录已截止')) throw new Error('Attendance supplement did not lock after 24 hours');
  await page.locator('#attendanceHistoryBody [data-attendance-history-select]').first().click();
  await page.locator('#attendanceHistoryBody [data-supplement-attendance]').click();
  if (!(await page.locator('#supplementDeadline').getByText('24 小时核对期').isVisible())) throw new Error('Attendance supplement deadline is missing');
  await page.locator('#attendanceSupplementForm input[name="actual"]').fill('195');
  await page.locator('#attendanceSupplementForm textarea[name="reason"]').fill('3名新进人员人脸信息延迟同步，现已核对补录');
  await page.locator('#attendanceSupplementForm input[name="supplementFile"]').setInputFiles({ name: '考勤补录依据.pdf', mimeType: 'application/pdf', buffer: Buffer.from('%PDF-1.4 supplement') });
  await page.locator('#attendanceSupplementForm').getByRole('button', { name: '保存核对补录' }).click();
  await page.locator('#attendanceSupplementDialog').waitFor({ state: 'hidden' });
  if (!(await page.locator('#attendanceHistoryBody').getByText('195 / 190 人').first().isVisible()) || !(await page.locator('#attendanceHistoryBody').getByText('核对补录记录 · 1').isVisible())) throw new Error('Attendance supplement was not recorded');
  await page.locator('#attendanceHistoryBody [data-supplement-file]').click();
  await page.locator('#attachmentPreviewDialog').waitFor({ state: 'visible' });
  await page.locator('#attachmentPreviewDialog').getByRole('button', { name: '关闭' }).first().click();
  await page.screenshot({ path: path.join(root, 'qa-attendance-history.png'), fullPage: true });
  await page.locator('#attendanceHistoryDialog').getByRole('button', { name: '关闭' }).first().click();
  await page.screenshot({ path: path.join(root, 'qa-organization-attendance.png'), fullPage: true });
  await page.locator('#globalBackButton').click();

  const recordText = `自动化现场照片记录-${Date.now()}`;
  await page.locator('#logButton').click();
  await page.locator('#photoInput').setInputFiles(sampleImageFile);
  await page.locator('#photoPreview img').waitFor();
  if (await page.locator('#photoPreview img').count() !== 1) throw new Error('Photo preview failed');
  await page.locator('#logForm textarea[name="content"]').fill(recordText);
  await page.screenshot({ path: path.join(root, 'qa-photo-record.png') });
  await page.locator('#logForm').getByRole('button', { name: '保存记录' }).click();
  await page.locator('#logDialog').waitFor({ state: 'hidden' });
  await page.locator('#logButton').click();
  await page.locator('#recentRecordsList').getByText(recordText).waitFor();
  await page.locator('#logDialog').getByRole('button', { name: '关闭' }).click();

  await page.evaluate(() => localStorage.clear());
  await page.reload();
  await page.waitForLoadState('networkidle');
  await login(page);
  await page.locator('#logButton').click();
  await page.locator('#recentRecordsList').getByText(recordText).waitFor();
  await page.locator('#logDialog').getByRole('button', { name: '关闭' }).click();
  await page.waitForTimeout(350);
  await page.screenshot({ path: path.join(root, 'qa-desktop.png'), fullPage: true });

  const mobile = await browser.newPage({ viewport: { width: 390, height: 844 } });
  await mobile.goto(url);
  await mobile.evaluate(() => { localStorage.clear(); sessionStorage.clear(); });
  await mobile.reload();
  await mobile.waitForLoadState('networkidle');
  if (!(await mobile.locator('#loginScreen').isVisible())) throw new Error('Mobile login page missing');
  await mobile.screenshot({ path: path.join(root, 'qa-login-mobile.png'), fullPage: true });
  await login(mobile);
  if (!(await mobile.locator('#menuButton').isVisible())) throw new Error('Mobile menu hidden');
  if (!(await mobile.locator('#addTaskButton').isVisible())) throw new Error('Dashboard new-task button hidden');
  await mobile.locator('#menuButton').click();
  if (!((await mobile.locator('#sidebar').getAttribute('class')) || '').includes('open')) throw new Error('Mobile menu failed');
  await mobile.locator('[data-view="tasks"]').click();
  await mobile.waitForTimeout(350);
  if (((await mobile.locator('#sidebar').getAttribute('class')) || '').includes('open')) throw new Error('Mobile sidebar did not close after navigation');
  if (!(await mobile.locator('#globalBackButton').isVisible())) throw new Error('Mobile back button hidden');
  if (await mobile.locator('#addTaskButton').isVisible()) throw new Error('Mobile new-task button should hide outside dashboard');
  await mobile.screenshot({ path: path.join(root, 'qa-mobile-back.png'), fullPage: true });
  await mobile.locator('#globalBackButton').click();
  if (!(await mobile.locator('#dashboard').isVisible())) throw new Error('Mobile back to dashboard failed');
  await mobile.locator('[data-id="1"] .task-status').click();
  if (!(await mobile.locator('#documentGateDialog').isVisible())) throw new Error('Mobile document gate did not open');
  const gateFitsViewport = await mobile.locator('#documentGateDialog').evaluate(dialog => dialog.scrollWidth <= dialog.clientWidth);
  if (!gateFitsViewport) throw new Error('Mobile document gate has horizontal overflow');
  await mobile.locator('#documentGateForm .gate-options label').first().click();
  if (!(await mobile.locator('#documentGateForm input[value="qualified"]').isChecked())) throw new Error('Mobile gate selection failed');
  await mobile.locator('#documentGateDialog').getByRole('button', { name: '关闭' }).click();
  await mobile.locator('#menuButton').click();
  await mobile.locator('[data-view="documents"]').click();
  if (await mobile.locator('#documents .material-acceptance-row:not(.header)').count() !== 4) throw new Error('Mobile material acceptance batches are not consolidated');
  await mobile.locator('#documents .material-acceptance-row:not(.header)').first().getByRole('button', { name: '查看 / 编辑' }).click();
  const acceptanceDialogFits = await mobile.locator('#materialAcceptanceDialog').evaluate(dialog => dialog.scrollWidth <= dialog.clientWidth);
  if (!acceptanceDialogFits) throw new Error('Mobile material acceptance dialog has horizontal overflow');
  await mobile.screenshot({ path: path.join(root, 'qa-mobile-material-acceptance.png'), fullPage: true });
  await mobile.locator('#materialAcceptanceDialog').getByRole('button', { name: '关闭' }).first().click();
  await mobile.locator('#menuButton').click();
  await mobile.locator('[data-view="materials"]').click();
  await mobile.locator('#materials [data-resource-tab="plans"]').click();
  if (!(await mobile.locator('#materials').getByText('未来 7 天到场预报').isVisible())) throw new Error('Mobile resource forecast hidden');
  await mobile.locator('#materials [data-resource-plan-detail]').first().click();
  const resourceDetailFits = await mobile.locator('#resourceDetailDialog').evaluate(dialog => dialog.scrollWidth <= dialog.clientWidth);
  if (!resourceDetailFits) throw new Error('Mobile resource detail has horizontal overflow');
  await mobile.screenshot({ path: path.join(root, 'qa-mobile-resource-detail.png'), fullPage: true });
  await mobile.locator('#resourceDetailDialog').getByRole('button', { name: '关闭' }).last().click();
  await mobile.locator('#menuButton').click();
  await mobile.locator('[data-view="quality"]').click();
  await mobile.locator('#quality [data-quality-filter="safety"]').click();
  await mobile.locator('#quality [data-edit-inspection]').first().click();
  const inspectionDialogFits = await mobile.locator('#inspectionBatchDialog').evaluate(dialog => dialog.scrollWidth <= dialog.clientWidth);
  if (!inspectionDialogFits) throw new Error('Mobile inspection batch dialog has horizontal overflow');
  await mobile.screenshot({ path: path.join(root, 'qa-mobile-inspection-batch.png'), fullPage: true });
  await mobile.locator('#inspectionBatchDialog').getByRole('button', { name: '关闭' }).first().click();
  await mobile.locator('#menuButton').click();
  await mobile.locator('[data-view="team"]').click();
  await mobile.waitForTimeout(350);
  if (!(await mobile.locator('#team .management-roster article').first().isVisible()) || !(await mobile.locator('#team [data-attendance]').isVisible())) throw new Error('Mobile organization/attendance content missing');
  await mobile.locator('#team [data-attendance]').click();
  await mobile.locator('#attendanceForm input[name="actual"]').fill('188');
  await mobile.locator('#attendanceForm input[name="planned"]').fill('190');
  await mobile.locator('#attendanceForm input[name="attendanceFile"]').setInputFiles({ name: '手机端考勤表.xlsx', mimeType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', buffer: xlsxBuffer });
  await mobile.locator('#attendanceForm').getByRole('button', { name: '保存考勤' }).click();
  await mobile.locator('#attendanceDialog').waitFor({ state: 'hidden' });
  await mobile.locator('#team [data-attendance-history]').first().click();
  const attendanceHistoryFits = await mobile.locator('#attendanceHistoryDialog').evaluate(dialog => dialog.scrollWidth <= dialog.clientWidth);
  if (!attendanceHistoryFits) throw new Error('Mobile attendance history dialog has horizontal overflow');
  await mobile.locator('#attendanceHistoryBody [data-supplement-attendance]').click();
  const supplementDialogFits = await mobile.locator('#attendanceSupplementDialog').evaluate(dialog => dialog.scrollWidth <= dialog.clientWidth);
  if (!supplementDialogFits) throw new Error('Mobile attendance supplement dialog has horizontal overflow');
  await mobile.screenshot({ path: path.join(root, 'qa-mobile-attendance-supplement.png'), fullPage: true });
  await mobile.locator('#attendanceSupplementDialog').getByRole('button', { name: '关闭' }).first().click();
  await mobile.screenshot({ path: path.join(root, 'qa-mobile-attendance-history.png'), fullPage: true });
  await mobile.locator('#attendanceHistoryDialog').getByRole('button', { name: '关闭' }).first().click();
  await mobile.screenshot({ path: path.join(root, 'qa-mobile-organization.png'), fullPage: true });
  await mobile.screenshot({ path: path.join(root, 'qa-mobile.png'), fullPage: true });
  await mobile.close();

  if (consoleErrors.length) throw new Error(`Console errors: ${consoleErrors.join(' | ')}`);
  console.log('PASS: desktop and mobile interactions verified');
  await browser.close();
})().catch(error => { console.error(error); process.exit(1); });
