(function (root, factory) {
  const rules = factory();
  if (typeof module === 'object' && module.exports) module.exports = rules;
  else root.ZhuxuMeetingRules = rules;
})(typeof globalThis !== 'undefined' ? globalThis : this, function () {
  const locked = record => Boolean(record?.meetingConfirmedAt);
  const progress = record => locked(record) ? Number(record.actualCompletion || 0) : 0;
  const identity = record => `${record.date}|${record.taskId}`;
  const protectedFields = ['taskId', 'dayPlanId', 'date', 'progress', 'actualCompletion', 'plannedTarget', 'achievedTarget', 'meetingConfirmedAt', 'meetingConfirmedBy', 'confirmed', 'scheduleSnapshot'];
  function confirm(record, plan, value, actor, now) {
    if (locked(record)) throw new Error('该项实际完成率已在例会确认并锁定，不能修改');
    if (value === null || value === '' || !Number.isFinite(Number(value)) || Number(value) < 0 || Number(value) > 100) throw new Error('请输入 0 到 100 之间的实际完成率');
    const actualCompletion = Number(value);
    const plannedTarget = Math.max(0, Math.min(100, Number(plan.dailyTarget ?? 100)));
    return { ...record, dayPlanId: plan.id, progress: actualCompletion, actualCompletion, plannedTarget,
      achievedTarget: Math.round(plannedTarget * actualCompletion) / 100,
      meetingConfirmedAt: now, meetingConfirmedBy: actor, confirmed: true, autoGenerated: false,
      scheduleSnapshot: plan.scheduleLink ? JSON.parse(JSON.stringify(plan.scheduleLink)) : null };
  }
  function validateUpdate(previous, next) {
    if (!Array.isArray(next)) throw new Error('每日执行记录格式无效');
    const keys = new Set(next.map(identity));
    if (keys.size !== next.length) throw new Error('同日同一任务不能重复登记完成率');
    for (const old of previous.filter(locked)) {
      const current = next.find(row => identity(row) === identity(old));
      if (!current || protectedFields.some(key => JSON.stringify(current[key]) !== JSON.stringify(old[key]))) throw new Error('已确认的例会完成率不能修改或删除');
    }
    for (const row of next.filter(locked)) {
      if (!previous.some(old => identity(old) === identity(row) && locked(old))) throw new Error('请通过每日例会确认实际完成率');
    }
  }
  const canSeeAll = user => /^(项目经理|技术负责人|生产经理)$/.test(String(user?.role || '').trim());
  function belongs(item, user) {
    if (!user) return false;
    if (item.ownerId) return String(item.ownerId) === String(user.id);
    const label = `${user.name} · ${user.role}`;
    return [item.owner, item.recipient].some(value => String(value || '').split(/[、,，;；]/).some(part => [label, user.name, user.role].includes(part.trim())));
  }
  function todos(state, user) {
    const list = [];
    const followups = state['zhuxu-followups'] || [];
    for (const item of followups.filter(item => !['done', 'resolved', 'closed'].includes(item.status))) list.push({ ...item, todoKey: `followup-${item.id}`, category: item.category || '协作待办', target: item.materialEntryId ? 'material' : item.workflowPlanId || item.resourcePlanId ? 'plan' : 'followup', targetId: item.materialEntryId || item.workflowPlanId || item.resourcePlanId || item.id });
    for (const item of (state['zhuxu-daily-coordination'] || []).filter(item => item.status !== 'resolved')) list.push({ ...item, todoKey: `coordination-${item.id}`, title: item.content, category: item.category || '协调事项', target: 'coordination', targetId: item.id });
    for (const plan of state['zhuxu-resource-plans'] || []) {
      const step = (plan.approvalWorkflow || []).find(step => step.status !== 'approved');
      if (!step || step.status !== 'pending' || list.some(item => String(item.workflowPlanId) === String(plan.id) && item.owner === step.owner)) continue;
      list.push({ todoKey: `approval-${plan.id}`, title: `审批：${plan.name}`, owner: step.owner, ownerId: step.ownerId, category: '材料审批', due: plan.due, note: `${step.role}待审批`, target: 'plan', targetId: plan.id });
    }
    for (const [key, chain] of Object.entries(state['zhuxu-document-state'] || {})) {
      for (const doc of chain.documents || []) {
        if (doc.status === 'done') continue;
        list.push({ todoKey: `document-${key}-${doc.id}`, title: doc.name, owner: doc.owner, category: '资料待办', due: doc.due, note: chain.linkedProcess, target: 'documents', targetId: key });
      }
    }
    for (const item of (state['zhuxu-quality-checks'] || []).filter(item => item.status !== 'closed')) list.push({ ...item, todoKey: `quality-${item.id}`, category: '质量整改', target: 'quality', targetId: item.id });
    return list.filter(item => canSeeAll(user) || belongs(item, user));
  }
  return { locked, progress, confirm, validateUpdate, todos, canSeeAll };
});
